#server:
#  port: 5000

upload:
  directory: data/
server:
  url: http://192.168.0.106:8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: ugp_clone_backend

  datasource:
    url: jdbc:mysql://localhost:3306/ugp_clone
    username: drillox
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          show_sql: true
          format_sql: true
